export const nftBalance = {
  blastOff: {
    packs: [
      "5",
      "66",
      "11231",
      "11232",
      "12418",
      "12419",
      "12420",
      "12421",
      "12422",
    ],
    cards: [
      {
        tokenId: "11000002",
        imageUrl: "001meownautC.png",
        number: 1,
        name: "Meownaut",
        type: "Psychic",
        description:
          "Legend says that the bioluminescent coin in a Meownaut's chest is the source of its resilience and good fortune.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Common",
        glbUrl: "/models/001meownautC.glb",
        set: "blastOff",
        packId: "5",
      },
      {
        tokenId: "29000001",
        imageUrl: "014changeteamsUC.png",
        number: 14,
        name: "Change Teams",
        type: "Supporter",
        description: "You don’t mind if I borrow this do you?",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Uncommon",
        glbUrl: "/models/014changeteamsUC.glb",
        set: "blastOff",
        packId: "5",
      },
      {
        tokenId: "48000001",
        imageUrl: "009kadalaxR.png",
        number: 9,
        name: "Kadalax",
        type: "Psychic",
        description:
          "Contrary to popular belief, it's not alway pleasant getting big spooned.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Rare",
        glbUrl: "/models/009kadalaxR.glb",
        set: "blastOff",
        packId: "5",
      },
      {
        tokenId: "37000002",
        imageUrl: "010kadalaxslimUC.png",
        number: 10,
        name: "Kadalax Slim",
        type: "Psychic",
        description:
          "Some Kadalax, having conquered their material vices, are able to sustain themselves off air and thought alone.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Uncommon",
        glbUrl: "/models/010kadalaxslimUC.glb",
        set: "blastOff",
        packId: "5",
      },
      {
        tokenId: "19000001",
        imageUrl: "014changeteamsC.png",
        number: 14,
        name: "Change Teams",
        type: "Supporter",
        description: "You don’t mind if I borrow this do you?",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Common",
        glbUrl: "/models/014changeteamsC.glb",
        set: "blastOff",
        packId: "5",
      },
      {
        tokenId: "34000006",
        imageUrl: "009kadalaxUC.png",
        number: 9,
        name: "Kadalax",
        type: "Psychic",
        description:
          "Contrary to popular belief, it's not alway pleasant getting big spooned.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Uncommon",
        glbUrl: "/models/009kadalaxUC.glb",
        set: "blastOff",
        packId: "66",
      },
      {
        tokenId: "18000013",
        imageUrl: "011zapduckC.png",
        number: 11,
        name: "Zapduck",
        type: "Lightning",
        description: "Strike one, you're out.",
        artist: {
          name: "Morlux",
          instagram: "@morlux_artista",
        },
        rarity: "Common",
        glbUrl: "/models/011zapduckC.glb",
        set: "blastOff",
        packId: "66",
      },
      {
        tokenId: "17000009",
        imageUrl: "012goldenkobanC.png",
        number: 12,
        name: "Golden Koban",
        type: "Item",
        description: "The only solution for inflation is production.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/012goldenkobanC.glb",
        set: "blastOff",
        packId: "66",
      },
      {
        tokenId: "14000012",
        imageUrl: "007blastardC.png",
        number: 7,
        name: "Blastard",
        type: "Fire",
        description: "Need a light?",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Common",
        glbUrl: "/models/007blastardC.glb",
        set: "blastOff",
        packId: "66",
      },
      {
        tokenId: "16000020",
        imageUrl: "004rattishC.png",
        number: 4,
        name: "Rattish",
        type: "Grass",
        description:
          "There are rodents who can cook, and those who teach Kung Fu. But some of them just wish to sit and contemplate the view.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Common",
        glbUrl: "/models/004rattishC.glb",
        set: "blastOff",
        packId: "66",
      },
      {
        tokenId: "16002524",
        imageUrl: "004rattishC.png",
        number: 4,
        name: "Rattish",
        type: "Grass",
        description:
          "There are rodents who can cook, and those who teach Kung Fu. But some of them just wish to sit and contemplate the view.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Common",
        glbUrl: "/models/004rattishC.glb",
        set: "blastOff",
        packId: "11231",
      },
      {
        tokenId: "19001237",
        imageUrl: "014changeteamsC.png",
        number: 14,
        name: "Change Teams",
        type: "Supporter",
        description: "You don’t mind if I borrow this do you?",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Common",
        glbUrl: "/models/014changeteamsC.glb",
        set: "blastOff",
        packId: "11231",
      },
      {
        tokenId: "25002503",
        imageUrl: "003pikapuffC.png",
        number: 3,
        name: "Pikapuff",
        type: "Lightning",
        description:
          "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/003pikapuffC.glb",
        set: "blastOff",
        packId: "11231",
      },
      {
        tokenId: "31001240",
        imageUrl: "001meownautUC.png",
        number: 1,
        name: "Meownaut",
        type: "Psychic",
        description:
          "Legend says that the bioluminescent coin in a Meownaut's chest is the source of its resilience and good fortune.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/001meownautUC.glb",
        set: "blastOff",
        packId: "11231",
      },
      {
        tokenId: "17001187",
        imageUrl: "012goldenkobanC.png",
        number: 12,
        name: "Golden Koban",
        type: "Item",
        description: "The only solution for inflation is production.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/012goldenkobanC.glb",
        set: "blastOff",
        packId: "11231",
      },
      {
        tokenId: "38001212",
        imageUrl: "005squirderUC.png",
        number: 5,
        name: "Squirder",
        type: "Fire",
        description:
          "Favorite start Pokemoon of the nicotine addicted trainer.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/005squirderUC.glb",
        set: "blastOff",
        packId: "11232",
      },
      {
        tokenId: "39001257",
        imageUrl: "003pikapuffUC.png",
        number: 3,
        name: "Pikapuff",
        type: "Lightning",
        description:
          "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/003pikapuffUC.glb",
        set: "blastOff",
        packId: "11232",
      },
      {
        tokenId: "32001268",
        imageUrl: "013goldenkobanUC.png",
        number: 13,
        name: "Golden Koban",
        type: "Item",
        description: "Lucky you.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/013goldenkobanUC.glb",
        set: "blastOff",
        packId: "11232",
      },
      {
        tokenId: "22002427",
        imageUrl: "005squirderC.png",
        number: 5,
        name: "Squirder",
        type: "Fire",
        description:
          "Favorite start Pokemoon of the nicotine addicted trainer.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Common",
        glbUrl: "/models/005squirderC.glb",
        set: "blastOff",
        packId: "11232",
      },
      {
        tokenId: "44000386",
        imageUrl: "011zapduckR.png",
        number: 11,
        name: "Zapduck",
        type: "Lightning",
        description: "Strike one, you're out.",
        artist: {
          name: "Morlux",
          instagram: "@morlux_artista",
        },
        rarity: "Rare",
        glbUrl: "/models/011zapduckR.glb",
        set: "blastOff",
        packId: "11232",
      },
      {
        tokenId: "15002704",
        imageUrl: "009kadalaxC.png",
        number: 9,
        name: "Kadalax",
        type: "Psychic",
        description:
          "Contrary to popular belief, it's not alway pleasant getting big spooned.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Common",
        glbUrl: "/models/009kadalaxC.glb",
        set: "blastOff",
        packId: "12418",
      },
      {
        tokenId: "11001345",
        imageUrl: "001meownautC.png",
        number: 1,
        name: "Meownaut",
        type: "Psychic",
        description:
          "Legend says that the bioluminescent coin in a Meownaut's chest is the source of its resilience and good fortune.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Common",
        glbUrl: "/models/001meownautC.glb",
        set: "blastOff",
        packId: "12418",
      },
      {
        tokenId: "33001284",
        imageUrl: "002pikapuffUC.png",
        number: 2,
        name: "Pikapuff",
        type: "Lightning",
        description: "That's gonna be a hit.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/002pikapuffUC.glb",
        set: "blastOff",
        packId: "12418",
      },
      {
        tokenId: "16002802",
        imageUrl: "004rattishC.png",
        number: 4,
        name: "Rattish",
        type: "Grass",
        description:
          "There are rodents who can cook, and those who teach Kung Fu. But some of them just wish to sit and contemplate the view.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Common",
        glbUrl: "/models/004rattishC.glb",
        set: "blastOff",
        packId: "12418",
      },
      {
        tokenId: "31001374",
        imageUrl: "001meownautUC.png",
        number: 1,
        name: "Meownaut",
        type: "Psychic",
        description:
          "Legend says that the bioluminescent coin in a Meownaut's chest is the source of its resilience and good fortune.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/001meownautUC.glb",
        set: "blastOff",
        packId: "12418",
      },
      {
        tokenId: "39001389",
        imageUrl: "003pikapuffUC.png",
        number: 3,
        name: "Pikapuff",
        type: "Lightning",
        description:
          "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/003pikapuffUC.glb",
        set: "blastOff",
        packId: "12419",
      },
      {
        tokenId: "33001285",
        imageUrl: "002pikapuffUC.png",
        number: 2,
        name: "Pikapuff",
        type: "Lightning",
        description: "That's gonna be a hit.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/002pikapuffUC.glb",
        set: "blastOff",
        packId: "12419",
      },
      {
        tokenId: "44000436",
        imageUrl: "011zapduckR.png",
        number: 11,
        name: "Zapduck",
        type: "Lightning",
        description: "Strike one, you're out.",
        artist: {
          name: "Morlux",
          instagram: "@morlux_artista",
        },
        rarity: "Rare",
        glbUrl: "/models/011zapduckR.glb",
        set: "blastOff",
        packId: "12419",
      },
      {
        tokenId: "24001384",
        imageUrl: "006chartortleC.png",
        number: 6,
        name: "Chartortle",
        type: "Fire",
        description:
          "Chartortles are known to reheat banana and anchovy pizza with the flame from their firey tails.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Common",
        glbUrl: "/models/006chartortleC.glb",
        set: "blastOff",
        packId: "12419",
      },
      {
        tokenId: "47000412",
        imageUrl: "004rattishR.png",
        number: 4,
        name: "Rattish",
        type: "Grass",
        description:
          "There are rodents who can cook, and those who teach Kung Fu. But some of them just wish to sit and contemplate the view.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Rare",
        glbUrl: "/models/004rattishR.glb",
        set: "blastOff",
        packId: "12419",
      },
      {
        tokenId: "32001406",
        imageUrl: "013goldenkobanUC.png",
        number: 13,
        name: "Golden Koban",
        type: "Item",
        description: "Lucky you.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/013goldenkobanUC.glb",
        set: "blastOff",
        packId: "12420",
      },
      {
        tokenId: "13002661",
        imageUrl: "015rashscratchumC.png",
        number: 15,
        name: "Rash Scratchum",
        type: "Supporter",
        description: "Ambition is an itch that is never truly satisfied.",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Common",
        glbUrl: "/models/015rashscratchumC.glb",
        set: "blastOff",
        packId: "12420",
      },
      {
        tokenId: "18002781",
        imageUrl: "011zapduckC.png",
        number: 11,
        name: "Zapduck",
        type: "Lightning",
        description: "Strike one, you're out.",
        artist: {
          name: "Morlux",
          instagram: "@morlux_artista",
        },
        rarity: "Common",
        glbUrl: "/models/011zapduckC.glb",
        set: "blastOff",
        packId: "12420",
      },
      {
        tokenId: "34001354",
        imageUrl: "009kadalaxUC.png",
        number: 9,
        name: "Kadalax",
        type: "Psychic",
        description:
          "Contrary to popular belief, it's not alway pleasant getting big spooned.",
        artist: {
          name: "Ilya",
          instagram: "@ilyaspb2019",
        },
        rarity: "Uncommon",
        glbUrl: "/models/009kadalaxUC.glb",
        set: "blastOff",
        packId: "12420",
      },
      {
        tokenId: "55000440",
        imageUrl: "008blastardR.png",
        number: 8,
        name: "Blastard",
        type: "Fire",
        description: "All Gas, Some brakes.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Rare",
        glbUrl: "/models/008blastardR.glb",
        set: "blastOff",
        packId: "12420",
      },
      {
        tokenId: "17001311",
        imageUrl: "012goldenkobanC.png",
        number: 12,
        name: "Golden Koban",
        type: "Item",
        description: "The only solution for inflation is production.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/012goldenkobanC.glb",
        set: "blastOff",
        packId: "12421",
      },
      {
        tokenId: "36001275",
        imageUrl: "012goldenkobanUC.png",
        number: 12,
        name: "Golden Koban",
        type: "Item",
        description: "The only solution for inflation is production.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/012goldenkobanUC.glb",
        set: "blastOff",
        packId: "12421",
      },
      {
        tokenId: "23001399",
        imageUrl: "008blastardC.png",
        number: 8,
        name: "Blastard",
        type: "Fire",
        description: "All Gas, Some brakes.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/008blastardC.glb",
        set: "blastOff",
        packId: "12421",
      },
      {
        tokenId: "32001407",
        imageUrl: "013goldenkobanUC.png",
        number: 13,
        name: "Golden Koban",
        type: "Item",
        description: "Lucky you.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/013goldenkobanUC.glb",
        set: "blastOff",
        packId: "12421",
      },
      {
        tokenId: "61000423",
        imageUrl: "003pikapuffL.png",
        number: 3,
        name: "Pikapuff",
        type: "Lightning",
        description:
          "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Legendary",
        glbUrl: "/models/003pikapuffL.glb",
        set: "blastOff",
        packId: "12421",
      },
      {
        tokenId: "38001330",
        imageUrl: "005squirderUC.png",
        number: 5,
        name: "Squirder",
        type: "Fire",
        description:
          "Favorite start Pokemoon of the nicotine addicted trainer.",
        artist: {
          name: "Armilo Barrios",
        },
        rarity: "Uncommon",
        glbUrl: "/models/005squirderUC.glb",
        set: "blastOff",
        packId: "12422",
      },
      {
        tokenId: "20002736",
        imageUrl: "013goldenkobanC.png",
        number: 13,
        name: "Golden Koban",
        type: "Item",
        description: "Lucky you.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Common",
        glbUrl: "/models/013goldenkobanC.glb",
        set: "blastOff",
        packId: "12422",
      },
      {
        tokenId: "52000418",
        imageUrl: "014changeteamsR.png",
        number: 14,
        name: "Change Teams",
        type: "Supporter",
        description: "You don’t mind if I borrow this do you?",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Rare",
        glbUrl: "/models/014changeteamsR.glb",
        set: "blastOff",
        packId: "12422",
      },
      {
        tokenId: "39001390",
        imageUrl: "003pikapuffUC.png",
        number: 3,
        name: "Pikapuff",
        type: "Lightning",
        description:
          "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
        artist: {
          name: "Lily&Ponto",
          instagram: "@lilloworks",
        },
        rarity: "Uncommon",
        glbUrl: "/models/003pikapuffUC.glb",
        set: "blastOff",
        packId: "12422",
      },
      {
        tokenId: "29001427",
        imageUrl: "014changeteamsUC.png",
        number: 14,
        name: "Change Teams",
        type: "Supporter",
        description: "You don’t mind if I borrow this do you?",
        artist: {
          name: "NinjaGuy",
        },
        rarity: "Uncommon",
        glbUrl: "/models/014changeteamsUC.glb",
        set: "blastOff",
        packId: "12422",
      },
    ],
  },
};
