import { PokemoonCard, PokemoonNft } from "./types";
import { ARTISTS, PM_RARITY, PM_TYPES } from ".";

export const BLAST_OFF_CARDS: PokemoonCard[] = [
  {
    number: 1,
    name: "Meownaut",
    type: PM_TYPES.PSYCHIC,
    description:
      "Legend says that the bioluminescent coin in a Meownaut's chest is the source of its resilience and good fortune.",
    artist: ARTISTS.Armilo,
  },
  {
    number: 2,
    name: "Pikapuff",
    type: PM_TYPES.LIGHTNING,
    description: "That's gonna be a hit.",
    artist: ARTISTS.LilyPonto,
  },
  {
    number: 3,
    name: "Pikapuff",
    type: PM_TYPES.LIGHTNING,
    description:
      "I woke up under the table with a splitting headache, smoke coming out of my ears... and an unconquerable urge to buy a ticket to her next show.",
    artist: ARTISTS.LilyPonto,
  },
  {
    number: 4,
    name: "Rattish",
    type: PM_TYPES.GRASS,
    description:
      "There are rodents who can cook, and those who teach Kung Fu. But some of them just wish to sit and contemplate the view.",
    artist: ARTISTS.Ilya,
  },
  {
    number: 5,
    name: "Squirder",
    type: PM_TYPES.FIRE,
    description: "Favorite start Pokemoon of the nicotine addicted trainer.",
    artist: ARTISTS.Armilo,
  },
  {
    number: 6,
    name: "Chartortle",
    type: PM_TYPES.FIRE,
    description:
      "Chartortles are known to reheat banana and anchovy pizza with the flame from their firey tails.",
    artist: ARTISTS.Armilo,
  },
  {
    number: 7,
    name: "Blastard",
    type: PM_TYPES.FIRE,
    description: "Need a light?",
    artist: ARTISTS.Armilo,
  },
  {
    number: 8,
    name: "Blastard",
    type: PM_TYPES.FIRE,
    description: "All Gas, Some brakes.",
    artist: ARTISTS.LilyPonto,
  },
  {
    number: 9,
    name: "Kadalax",
    type: PM_TYPES.PSYCHIC,
    description:
      "Contrary to popular belief, it's not alway pleasant getting big spooned.",
    artist: ARTISTS.Ilya,
  },
  {
    number: 10,
    name: "Kadalax Slim",
    type: PM_TYPES.PSYCHIC,
    description:
      "Some Kadalax, having conquered their material vices, are able to sustain themselves off air and thought alone.",
    artist: ARTISTS.Ilya,
  },
  {
    number: 11,
    name: "Zapduck",
    type: PM_TYPES.LIGHTNING,
    description: "Strike one, you're out.",
    artist: ARTISTS.Morlux,
  },
  {
    number: 12,
    name: "Golden Koban",
    type: PM_TYPES.ITEM,
    description: "",
    artist: ARTISTS.LilyPonto,
  },
  {
    number: 13,
    name: "Golden Koban",
    type: PM_TYPES.ITEM,
    description: "",
    artist: ARTISTS.LilyPonto,
  },
  {
    number: 14,
    name: "Change Teams",
    type: PM_TYPES.SUPPORTER,
    description: "",
    artist: ARTISTS.NinjaGuy,
  },
  {
    number: 15,
    name: "Rash Scratchum",
    type: PM_TYPES.SUPPORTER,
    description: "",
    artist: ARTISTS.NinjaGuy,
  },
  {
    number: 16,
    name: "Baby Meownaut",
    type: PM_TYPES.PSYCHIC,
    description: "It's too adorable for words.",
    artist: ARTISTS.Mathijs,
  },
];

const NFT_LIST: PokemoonNft[] = [
  {
    tokenId: "11000000",
    imageUrl: "001meownautC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 1),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "12000000",
    imageUrl: "001meownautUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 1),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "13000000",
    imageUrl: "001meownautR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 1),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "14000000",
    imageUrl: "001meownautL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 1),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "15000000",
    imageUrl: "002pikapuffC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 2),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "16000000",
    imageUrl: "002pikapuffUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 2),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "17000000",
    imageUrl: "002pikapuffR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 2),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "18000000",
    imageUrl: "003pikapuffC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 3),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "19000000",
    imageUrl: "003pikapuffUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 3),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "20000000",
    imageUrl: "003pikapuffR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 3),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "21000000",
    imageUrl: "003pikapuffL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 3),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "22000000",
    imageUrl: "004rattishC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 4),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "23000000",
    imageUrl: "004rattishUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 4),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "24000000",
    imageUrl: "004rattishR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 4),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "25000000",
    imageUrl: "005squirderC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 5),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "26000000",
    imageUrl: "005squirderUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 5),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "27000000",
    imageUrl: "005squirderR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 5),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "28000000",
    imageUrl: "006chartortleC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 6),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "29000000",
    imageUrl: "006chartortleUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 6),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "30000000",
    imageUrl: "006chartortleR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 6),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "31000000",
    imageUrl: "007blastardC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 7),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "32000000",
    imageUrl: "007blastardUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 7),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "33000000",
    imageUrl: "007blastardR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 7),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "34000000",
    imageUrl: "008blastardC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 8),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "35000000",
    imageUrl: "008blastardUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 8),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "36000000",
    imageUrl: "008blastardR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 8),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "37000000",
    imageUrl: "008blastardL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 8),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "38000000",
    imageUrl: "009kadalaxC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 9),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "39000000",
    imageUrl: "009kadalaxUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 9),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "40000000",
    imageUrl: "009kadalaxR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 9),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "41000000",
    imageUrl: "010kadalaxslimC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 10),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "42000000",
    imageUrl: "010kadalaxslimUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 10),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "43000000",
    imageUrl: "010kadalaxslimR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 10),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "44000000",
    imageUrl: "011zapduckC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 11),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "45000000",
    imageUrl: "011zapduckUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 11),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "46000000",
    imageUrl: "011zapduckR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 11),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "47000000",
    imageUrl: "011zapduckL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 11),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "48000000",
    imageUrl: "012goldenkobanC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 12),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "49000000",
    imageUrl: "012goldenkobanUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 12),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "50000000",
    imageUrl: "012goldenkobanR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 12),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "51000000",
    imageUrl: "013goldenkobanC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 13),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "52000000",
    imageUrl: "013goldenkobanUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 13),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "53000000",
    imageUrl: "013goldenkobanR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 13),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "54000000",
    imageUrl: "014changeteamsC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 14),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "55000000",
    imageUrl: "014changeteamsUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 14),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "56000000",
    imageUrl: "014changeteamsR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 14),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "57000000",
    imageUrl: "014changeteamsL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 14),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "58000000",
    imageUrl: "015rashscratchumC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 15),
    rarity: PM_RARITY.C,
  },
  {
    tokenId: "59000000",
    imageUrl: "015rashscratchumUC.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 15),
    rarity: PM_RARITY.U,
  },
  {
    tokenId: "60000000",
    imageUrl: "015rashscratchumR.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 15),
    rarity: PM_RARITY.R,
  },
  {
    tokenId: "61000000",
    imageUrl: "015rashscratchumL.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 15),
    rarity: PM_RARITY.L,
  },
  {
    tokenId: "62000000",
    imageUrl: "016babymeownautML.png",
    card: BLAST_OFF_CARDS.find((card) => card.number === 16),
    rarity: PM_RARITY.M,
  },
];

export default NFT_LIST;
